apiVersion: operators.example.com/v1
kind: RateLimiterConfig
metadata:
  name: host-info-srv-config
spec:
  rateLimiter: "rate-limiter"
  applyTo: "GATEWAY"
  host: "host-info-srv.org"
  port: 80
  failureModeDeny: false
  workloadSelector:
    labels:
      istio: ingressgateway
  descriptors:
    - key: custom-rl-header
      value: setting1
      rate_limit:
        unit: minute
        requests_per_unit: 1
  rateLimits:
    - actions:
        - generic_key:
            descriptor_value: counters
    - actions:
        - request_headers:
            descriptor_key: custom-rl-header
            header_name: custom-rl-header






















#  applyTo: "SIDECAR_OUTBOUND"
#  host: "endpoint-app.operator-test.svc.cluster.local"
#  port: 80
#  workloadSelector:
#    labels:
#      app: intermediary-app
#  failureModeDeny: false
#  rateLimitProperty:
#    domain: intermediary-app
#    descriptors:
#      - key: custom-rl-header
#        value: setting1
#        rate_limit:
#          unit: minute
#          requests_per_unit: 1
