apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ratelimit-operator
  template:
    metadata:
      labels:
        name: ratelimit-operator
      annotations:
        prometheus_io_port: '8383'
        prometheus_io_scheme: http
        prometheus_io_scrape: 'true'
    spec:
      serviceAccountName: ratelimit-operator
      containers:
        - name: ratelimit-operator
          # Replace this with the built image name
          image: voteva/ratelimit-operator:v0.0.1
          command:
          - ratelimit-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ratelimit-operator"
